const API=window.TURBO_API||location.origin;let token=localStorage.getItem('turbo_token')||'';let pub=null,me=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
async function api(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};if(token)h.authorization=`Bearer ${token}`;const r=await fetch(API+path,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||'ERROR'),{status:r.status,data:j});return j}
function consumeToken(){const h=new URLSearchParams(location.hash.slice(1));if(h.get('token')){token=h.get('token');localStorage.setItem('turbo_token',token);history.replaceState(null,'',location.pathname+location.search+'#home')}}
function statusText(s){return({pending:'قيد المراجعة',pre_accepted:'مقبول مبدئيًا',voice_passed:'مقبول نهائيًا — تصريح الدخول',rejected:'مرفوض',reset:'مسموح بإعادة التقديم'})[s]||s}
async function init(){consumeToken();pub=await api('/api/public');renderPublic();if(token){try{me=await api('/api/me');renderMe()}catch{localStorage.removeItem('turbo_token');token='';renderApply()}}else renderApply()}
function renderPublic(){$('#aboutText').textContent=pub.settings.aboutText;$('#rulesList').innerHTML=pub.settings.rules.map((r,i)=>`<div class="rule"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(r)}</span></div>`).join('');$('#creatorGrid').innerHTML=pub.creators.length?pub.creators.map(c=>`<a class="creator" href="${esc(c.url)}" target="_blank" rel="noopener"><img src="${esc(c.image||'')}" alt="${esc(c.name)}"><div class="meta"><h3>${esc(c.name)}</h3>${c.isLive?'<span class="live">LIVE الآن</span>':'<span class="offline">غير مباشر الآن</span>'}</div></a>`).join(''):'<div class="notice">سيتم إضافة صناع المحتوى من لوحة التحكم.</div>';$('#applyState').textContent=pub.settings.applicationsOpen?'التقديم مفتوح الآن':'التقديم مغلق حاليًا'}
function renderMe(){$('#loginBtn').textContent=`${me.user.globalName||me.user.username} • خروج`;$('#loginBtn').onclick=()=>{localStorage.removeItem('turbo_token');location.reload()};if(me.isAdmin){$('#adminLink').classList.remove('hidden');$('#admin').classList.remove('hidden');renderAdmin()}renderApply();renderStatus()}
function renderApply(){const box=$('#applyBox');if(!token){box.innerHTML=`<div class="notice">سجّل دخول بحساب Discord أولًا علشان الموقع والبوت يعرفوا حسابك.</div><br><button class="discord" onclick="location.href='${API}/auth/discord'">تسجيل الدخول بـ Discord</button>`;$('#loginBtn').onclick=()=>location.href=`${API}/auth/discord`;return}if(!pub.settings.applicationsOpen){box.innerHTML='<div class="notice bad">التقديم مغلق حاليًا من الإدارة.</div>';return}if(me&&!me.canApply){let extra='';if(me.latest?.status==='rejected'&&me.waitMs>0)extra=`<p>تقدر تقدم تاني بعد: <b id="countdown"></b></p>`;box.innerHTML=`<div class="notice">زر التقديم غير متاح لحسابك حاليًا. ${extra}</div>`;if(me.waitMs>0)countdown();return}
 box.innerHTML=`<form id="applyForm"><div class="form-grid"><div class="field"><label>الاسم الحقيقي ثنائي</label><input name="realName" required placeholder="الاسم الأول واسم العائلة"></div><div class="field"><label>العمر</label><input name="age" type="number" min="16" max="80" required></div><div class="field full"><label>قصة الشخصية</label><textarea name="story" minlength="120" required placeholder="اكتب قصة شخصيتك بنفسك... مين هي؟ جاية منين؟ وإيه هدفها في المدينة؟"></textarea></div></div><h3>أسئلة الرول بلاي</h3>${pub.questions.map((q,i)=>`<div class="question"><strong>${i+1}. ${esc(q)}</strong><textarea name="q${i}" required minlength="10"></textarea></div>`).join('')}<br><button class="primary" type="submit">إرسال التقديم</button></form>`;$('#applyForm').onsubmit=submitApply}
async function submitApply(e){e.preventDefault();const f=new FormData(e.target);const body={realName:f.get('realName'),age:Number(f.get('age')),story:f.get('story'),answers:pub.questions.map((_,i)=>f.get('q'+i))};try{const j=await api('/api/applications',{method:'POST',body:JSON.stringify(body)});toast(`تم إرسال التقديم رقم #${j.application.number}`);me=await api('/api/me');renderMe();location.hash='status'}catch(e){toast(errorArabic(e.message))}}
function errorArabic(e){return({REAL_NAME_TWO_PARTS:'اكتب الاسم الحقيقي ثنائي.',INVALID_AGE:'العمر غير صحيح.',STORY_TOO_SHORT:'قصة الشخصية قصيرة جدًا.',ANSWERS_INCOMPLETE:'كمّل كل أسئلة الرول بلاي.',COOLDOWN:'لسه مدة الـ12 ساعة مخلصتش.',BLOCKED:'عندك تقديم قائم بالفعل.',CLOSED:'التقديم مغلق.'})[e]||'حصل خطأ. جرّب تاني.'}
function countdown(){const end=Date.now()+me.waitMs;const tick=()=>{const el=$('#countdown');if(!el)return;const d=Math.max(0,end-Date.now()),h=Math.floor(d/3600000),m=Math.floor(d%3600000/60000),s=Math.floor(d%60000/1000);el.textContent=`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(d<=0)setTimeout(()=>location.reload(),1000)};tick();setInterval(tick,1000)}
function renderStatus(){const box=$('#statusBox');if(!token){box.innerHTML='<div class="notice">سجّل دخول علشان تشوف حالة تقديمك.</div>';return}if(!me.latest){box.innerHTML='<div class="notice">لسه ما قدمتش.</div>';return}const a=me.latest;let x=`<div class="status-card"><span class="tag">تقديم #${a.number}</span><h3>${statusText(a.status)}</h3><div>الاسم: <b>${esc(a.realName)}</b></div>`;if(a.status==='pending')x+='<div class="notice">طلبك وصل لروم المراجعة ومستني قرار الإدارة.</div>';if(a.status==='rejected')x+=`<div class="notice bad"><b>سبب الرفض:</b><br>${esc(a.reason||'لم يتم تحديد سبب')}</div>`;if(a.status==='pre_accepted'){x+='<div class="notice good">تم قبولك مبدئيًا. الخطوة الجاية هي المقابلة الصوتية.</div>';if(me.booked)x+=`<div class="notice">موعدك المحجوز: <b>${new Date(me.booked.at).toLocaleString('ar-EG')}</b><br>${esc(me.booked.note||'')}</div>`;else x+=`<h3>اختار موعد المقابلة</h3><div class="list">${pub.interviewSlots.length?pub.interviewSlots.map(s=>`<div class="item"><span>${new Date(s.at).toLocaleString('ar-EG')}<br><small>${esc(s.note||'')}</small></span><button class="smallbtn" onclick="bookSlot('${s.id}')">حجز</button></div>`).join(''):'<div class="notice">لا توجد مواعيد متاحة حاليًا.</div>'}</div>`}if(a.status==='voice_passed')x+='<div class="notice good">✅ تم قبولك في المقابلة ومنحك رول تصريح الدخول.</div>';box.innerHTML=x+'</div>'}
window.bookSlot=async id=>{try{await api(`/api/interviews/${id}/book`,{method:'POST',body:'{}'});toast('تم حجز الموعد');me=await api('/api/me');pub=await api('/api/public');renderStatus()}catch{toast('الموعد غير متاح')}};
async function renderAdmin(){const st=await api('/api/admin/state');$('#adminBox').innerHTML=`<div class="admin-grid"><div class="card"><h3>التقديم</h3><p>الحالة: <b>${st.settings.applicationsOpen?'مفتوح':'مغلق'}</b></p><button class="${st.settings.applicationsOpen?'danger':'primary'}" onclick="toggleApps(${!st.settings.applicationsOpen})">${st.settings.applicationsOpen?'قفل التقديم':'فتح التقديم'}</button></div><div class="card"><h3>الطلبات</h3><div class="list">${[...st.applications].reverse().slice(0,20).map(a=>`<div class="item"><span>#${a.number} ${esc(a.realName)}<br><small>${statusText(a.status)} • ${a.discordId}</small></span><span>${a.status==='pre_accepted'?`<button class="smallbtn" onclick="voicePass('${a.discordId}')">نجح بالمقابلة</button>`:''} <button class="smallbtn" onclick="resetUser('${a.discordId}')">سماح بإعادة التقديم</button></span></div>`).join('')||'لا يوجد'}</div></div><div class="card"><h3>إضافة صانع محتوى</h3><form id="creatorForm" class="form-grid"><div class="field"><input name="name" placeholder="الاسم" required></div><div class="field"><input name="order" type="number" placeholder="الترتيب" value="1"></div><div class="field full"><input name="image" placeholder="لينك الصورة" required></div><div class="field full"><input name="url" placeholder="لينك الصفحة" required></div><div class="field"><select name="platform"><option value="youtube">YouTube</option><option value="twitch">Twitch</option><option value="other">Other</option></select></div><div class="field"><input name="platformId" placeholder="Channel ID / Twitch login"></div><button class="primary" type="submit">إضافة</button></form><div class="list">${st.creators.map(c=>`<div class="item"><span>${esc(c.name)} ${c.isLive?'🔴':''}</span><button class="danger" onclick="delCreator('${c.id}')">حذف</button></div>`).join('')}</div></div><div class="card"><h3>مواعيد المقابلات</h3><form id="slotForm"><div class="field"><input name="at" type="datetime-local" required></div><div class="field"><input name="note" placeholder="ملاحظة / روم المقابلة"></div><br><button class="primary">إضافة موعد</button></form><div class="list">${st.interviewSlots.map(s=>`<div class="item"><span>${new Date(s.at).toLocaleString('ar-EG')} ${s.bookedBy?'• محجوز':''}</span>${!s.bookedBy?`<button class="danger" onclick="delSlot('${s.id}')">حذف</button>`:''}</div>`).join('')}</div></div></div>`;$('#creatorForm').onsubmit=addCreator;$('#slotForm').onsubmit=addSlot}
window.toggleApps=async v=>{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({applicationsOpen:v})});pub=await api('/api/public');renderPublic();renderAdmin();toast(v?'تم فتح التقديم':'تم قفل التقديم')};
window.voicePass=async id=>{await api(`/api/admin/users/${id}/voice-pass`,{method:'POST',body:'{}'});toast('تم منح تصريح الدخول');renderAdmin()};window.resetUser=async id=>{await api(`/api/admin/users/${id}/reset`,{method:'POST',body:'{}'});toast('تم السماح بإعادة التقديم');renderAdmin()};
async function addCreator(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await api('/api/admin/creators',{method:'POST',body:JSON.stringify(f)});toast('تمت إضافة صانع المحتوى');pub=await api('/api/public');renderPublic();renderAdmin()}window.delCreator=async id=>{await api(`/api/admin/creators/${id}`,{method:'DELETE'});renderAdmin();pub=await api('/api/public');renderPublic()};
async function addSlot(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await api('/api/admin/interviews',{method:'POST',body:JSON.stringify(f)});toast('تمت إضافة الموعد');pub=await api('/api/public');renderAdmin();renderStatus()}window.delSlot=async id=>{await api(`/api/admin/interviews/${id}`,{method:'DELETE'});pub=await api('/api/public');renderAdmin()};
$('#menu').onclick=()=>$('#nav').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));init().catch(e=>{console.error(e);toast('تعذر الاتصال بالسيرفر')});
