(()=>{
 document.body.classList.add('legend-v4');
 const team=document.querySelector('#team');
 if(team){const lead=team.querySelector('.section-lead');if(lead)lead.textContent='أشخاص بيجمعهم هدف واحد: مدينة تستحق قصتك.';const note=team.querySelector('.section-head>p');if(note)note.textContent='الفريق اللي بيصنع التجربة';}
 const grid=document.querySelector('#teamGrid');let selected=0,touchX=0;
 function position(){if(!grid)return;const cards=[...grid.querySelectorAll('.team-card')];const controls=grid.nextElementSibling;if(controls)controls.hidden=!cards.length;if(!cards.length)return;selected=(selected+cards.length)%cards.length;cards.forEach((c,i)=>{let offset=i-selected;if(offset>cards.length/2)offset-=cards.length;if(offset<-cards.length/2)offset+=cards.length;c.style.setProperty('--offset',offset);c.style.setProperty('--abs',Math.abs(offset));c.style.zIndex=String(10-Math.abs(offset));c.classList.toggle('team-active',offset===0);c.classList.toggle('team-away',Math.abs(offset)>2);c.setAttribute('aria-current',offset===0?'true':'false');c.tabIndex=Math.abs(offset)>2?-1:0;c.setAttribute('role','button');c.setAttribute('aria-label','عرض '+(c.querySelector('h3')?.textContent||'العضو'));});const current=cards[selected];const info=document.querySelector('#legendTeamCurrent');if(info){info.replaceChildren();const h=document.createElement('h3');h.textContent=current.querySelector('h3')?.textContent||'';const b=document.createElement('p');b.textContent=current.querySelector('.team-info b')?.textContent||'';info.append(h,b);}const prev=document.querySelector('#legendTeamPrev'),next=document.querySelector('#legendTeamNext');if(prev)prev.disabled=cards.length<2;if(next)next.disabled=cards.length<2;}
 if(grid){grid.classList.add('legend-team-stage');const controls=document.createElement('div');controls.className='legend-team-controls';controls.innerHTML='<button id="legendTeamPrev" type="button" aria-label="العضو السابق">السابق ←</button><div id="legendTeamCurrent" aria-live="polite"></div><button id="legendTeamNext" type="button" aria-label="العضو التالي">→ التالي</button>';grid.after(controls);controls.querySelector('#legendTeamPrev').onclick=()=>{selected--;position();};controls.querySelector('#legendTeamNext').onclick=()=>{selected++;position();};grid.addEventListener('click',e=>{const c=e.target.closest('.team-card');if(c){selected=[...grid.querySelectorAll('.team-card')].indexOf(c);position();}});grid.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selected+=e.key==='ArrowLeft'?1:-1;position();}if(e.key==='Enter'||e.key===' '){const c=e.target.closest('.team-card');if(c){e.preventDefault();selected=[...grid.querySelectorAll('.team-card')].indexOf(c);position();}}});grid.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});grid.addEventListener('touchend',e=>{const diff=e.changedTouches[0].clientX-touchX;if(Math.abs(diff)>45){selected+=diff>0?-1:1;position();}},{passive:true});new MutationObserver(()=>{selected=0;position();}).observe(grid,{childList:true});position();}
 const links=document.querySelectorAll('#nav a');const sections=[...document.querySelectorAll('main section[id]')];if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('legend-nav-active',a.getAttribute('href')==='#'+entry.target.id));}},{rootMargin:'-20% 0px -55% 0px'});sections.forEach(s=>observer.observe(s));}
 const header=document.querySelector('.topbar');window.addEventListener('scroll',()=>header?.classList.toggle('legend-scrolled',scrollY>30),{passive:true});
})();
