// Store uses the same authenticated sessions and persistent DB as the existing site.
export function installStore({app,auth,admin,readDB,mutate,dm,frontendUrl,crypto,asyncRoute}) {
 const init=db=>{db.storeProducts??=[];db.storeOrders??=[];db.storeTickets??=[];};
 const fail=(code,status=400)=>{throw Object.assign(new Error(code),{status});};
 const text=(v,n=2000)=>String(v??'').trim().slice(0,n);
 const id=()=>crypto.randomUUID();
 const run=fn=>asyncRoute(async(req,res)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({error:e.message});throw e;}});
 const notify=async(order,content)=>{let ok=false;try{ok=await dm(order.discordId,{content:`${content}\nطلب #${order.number}: ${order.product.name}\n${frontendUrl}/#store`});}catch{}await mutate(db=>{init(db);const o=db.storeOrders.find(x=>x.id===order.id);if(o)o.dmStatus=ok?'sent':'failed';});return ok;};
 const realUser=req=>{if(!/^\d{15,22}$/.test(req.user.id))fail('DISCORD_LOGIN_REQUIRED',403);};
 app.get('/api/store',run(async(req,res)=>{const db=await readDB();init(db);res.json({products:db.storeProducts.filter(p=>p.active)});}));
 app.get('/api/store/mine',auth,run(async(req,res)=>{const db=await readDB();init(db);res.json({orders:db.storeOrders.filter(o=>o.discordId===req.user.id),tickets:db.storeTickets.filter(t=>t.discordId===req.user.id)});}));
 app.get('/api/admin/store',auth,admin,run(async(req,res)=>{const db=await readDB();init(db);res.json({products:db.storeProducts,orders:db.storeOrders,tickets:db.storeTickets});}));
 app.post('/api/admin/store/products',auth,admin,run(async(req,res)=>{
 const b=req.body;const name=text(b.name,120),image=text(b.image,2000);if(!name||!image)fail('NAME_IMAGE_REQUIRED');try{const u=new URL(image);if(!['https:','http:'].includes(u.protocol))throw 0;}catch{fail('INVALID_IMAGE_URL');}
 const product=await mutate(db=>{init(db);let p=b.id?db.storeProducts.find(x=>x.id===b.id):null;if(b.id&&!p)fail('PRODUCT_NOT_FOUND',404);if(!p){p={id:id(),createdAt:Date.now()};db.storeProducts.push(p);}Object.assign(p,{name,image,details:text(b.details),note:text(b.note),type:text(b.type,100)||'منتج',delivery:text(b.delivery,500)||'بالتنسيق مع الدعم',price:text(b.price,80),active:b.active!==false});return structuredClone(p);});res.json({product});
 }));
 app.delete('/api/admin/store/products/:id',auth,admin,run(async(req,res)=>{await mutate(db=>{init(db);const p=db.storeProducts.find(x=>x.id===req.params.id);if(!p)fail('PRODUCT_NOT_FOUND',404);p.active=false;});res.json({ok:true});}));
 app.post('/api/store/orders',auth,run(async(req,res)=>{realUser(req);const order=await mutate(db=>{init(db);const p=db.storeProducts.find(x=>x.id===req.body.productId&&x.active);if(!p)fail('PRODUCT_NOT_FOUND',404);const existing=db.storeOrders.find(x=>x.discordId===req.user.id&&x.product.id===p.id&&x.status==='pending');if(existing)fail('ORDER_ALREADY_PENDING',409);const o={id:id(),number:(db.counters.storeOrder=(db.counters.storeOrder||0)+1),discordId:req.user.id,username:req.user.username,product:structuredClone(p),customerNote:text(req.body.note),status:'pending',createdAt:Date.now(),dmStatus:'pending'};db.storeOrders.push(o);return structuredClone(o);});const dmSent=await notify(order,'طلبك قيد المراجعة. هنعرفك أول ما الإدارة تراجعه.');res.json({order,dmSent});}));
 app.post('/api/admin/store/orders/:id/review',auth,admin,run(async(req,res)=>{const action=req.body.action,reason=text(req.body.reason);if(!['accept','reject'].includes(action))fail('INVALID_ACTION');if(action==='reject'&&!reason)fail('REASON_REQUIRED');const order=await mutate(db=>{init(db);const o=db.storeOrders.find(x=>x.id===req.params.id);if(!o)fail('ORDER_NOT_FOUND',404);if(o.status!=='pending')fail('ORDER_ALREADY_REVIEWED',409);o.status=action==='accept'?'accepted':'rejected';o.reason=reason;o.reviewedBy=req.user.id;o.reviewedAt=Date.now();if(action==='accept'){const t={id:id(),orderId:o.id,number:o.number,discordId:o.discordId,product:structuredClone(o.product),customerNote:o.customerNote,status:'open',createdAt:Date.now(),messages:[{id:id(),sender:'system',name:'النظام',text:'تم قبول الطلب. الدعم هيتواصل معاك هنا لتنسيق الاستلام.',at:Date.now()}]};db.storeTickets.push(t);o.ticketId=t.id;}db.audit.push({at:Date.now(),by:req.user.id,action:'store_order_'+action,orderId:o.id,reason});return structuredClone(o);});const dmSent=await notify(order,action==='accept'?'تم قبول طلبك وفتح تذكرة استلام في الموقع.':'تم رفض طلبك. السبب: '+reason);res.json({order,dmSent});}));
 async function access(req,db){init(db);const t=db.storeTickets.find(x=>x.id===req.params.id);if(!t)fail('TICKET_NOT_FOUND',404);let staff=false;if(t.discordId!==req.user.id){await new Promise((resolve,reject)=>admin(req,{status:()=>({json:()=>reject(Object.assign(new Error('FORBIDDEN'),{status:403}))})},e=>e?reject(e):resolve()));staff=true;}return {t,staff};}
 app.post('/api/store/tickets/:id/messages',auth,run(async(req,res)=>{const message=text(req.body.message);if(!message)fail('MESSAGE_REQUIRED');let recipient;await mutate(async db=>{const {t,staff}=await access(req,db);if(t.status!=='open')fail('TICKET_CLOSED',409);if(t.messages.length>=2000)fail('TICKET_MESSAGE_LIMIT',409);t.messages.push({id:id(),sender:staff?'support':'customer',name:req.user.globalName||req.user.username,text:message,at:Date.now()});recipient=staff?t.discordId:null;});if(recipient)try{await dm(recipient,{content:`الدعم رد على تذكرة الاستلام الخاصة بك.\n${frontendUrl}/#store`});}catch{}res.json({ok:true});}));
 app.post('/api/store/tickets/:id/action',auth,run(async(req,res)=>{await mutate(async db=>{const {t}=await access(req,db);if(req.body.action==='close'){t.status='closed';t.closedAt=Date.now();t.closedBy=req.user.id;}else if(req.body.action==='delete'){if(t.status!=='closed')fail('CLOSE_TICKET_FIRST',409);db.storeTickets=db.storeTickets.filter(x=>x.id!==t.id);const o=db.storeOrders.find(x=>x.id===t.orderId);if(o){o.ticketDeleted=true;}}else fail('INVALID_ACTION');});res.json({ok:true});}));
}
