(()=>{
let state={products:[],orders:[],tickets:[]},staff=false,busy=false;
const labels={pending:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض',open:'مفتوحة',closed:'مغلقة'};
const section=document.createElement('section');section.id='store';section.className='store-section';section.dir='rtl';section.innerHTML='<h2>متجر Legend</h2><p>اختار المنتج وأكد الطلب. الإدارة هتراجعه، وبعد القبول هتفتح تذكرة للاستلام.</p><div id="storeContent">جاري التحميل…</div>';
(document.querySelector('main')||document.body).append(section);
const nav=document.querySelector('#nav');if(nav){const a=document.createElement('a');a.href='#store';a.textContent='المتجر';nav.append(a);}
const safe=fn=>async(...args)=>{try{await fn(...args);}catch(e){const m={DISCORD_LOGIN_REQUIRED:'سجل دخول بحساب ديسكورد للشراء',ORDER_ALREADY_PENDING:'عندك طلب لنفس المنتج قيد المراجعة',ORDER_ALREADY_REVIEWED:'الطلب اتراجع بالفعل',REASON_REQUIRED:'اكتب سبب الرفض',CLOSE_TICKET_FIRST:'اقفل التذكرة قبل حذفها',TICKET_CLOSED:'التذكرة مغلقة',LOGIN_REQUIRED:'سجل دخول بديسكورد الأول',INVALID_IMAGE_URL:'لينك الصورة غير صحيح'};toast(m[e.message]||'تعذر تنفيذ العملية: '+e.message);}};
const post=(url,body)=>api(url,{method:'POST',body:JSON.stringify(body)});
function detail(p){return `<h3>${esc(p.name)}</h3>${p.price?`<p>السعر: ${esc(p.price)}</p>`:''}<p>النوع: ${esc(p.type)}</p><p>الاستلام: ${esc(p.delivery)}</p>${p.details?`<p class="store-lines">${esc(p.details)}</p>`:''}${p.note?`<p>ملحوظة: ${esc(p.note)}</p>`:''}`;}
async function load(){if(busy)return;busy=true;try{const catalog=await api('/api/store');staff=!!me?.isAdmin;let personal={orders:[],tickets:[]};if(token)personal=await api(staff?'/api/admin/store':'/api/store/mine');state={...personal,products:staff?personal.products:catalog.products};render();}finally{busy=false;}}
function render(){document.querySelector('#storeContent').innerHTML=`${staff?'<button class="btn primary" data-store="edit" data-id="">إضافة منتج</button>':''}<div class="store-grid">${state.products.map(p=>`<article class="store-card"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" referrerpolicy="no-referrer">${detail(p)}${staff?`<span>${p.active?'متاح':'مخفي'}</span><button data-store="edit" data-id="${p.id}">تعديل</button><button data-store="hide" data-id="${p.id}">إخفاء المنتج</button>`:`<button class="btn primary" data-store="buy" data-id="${p.id}">شراء</button>`}</article>`).join('')||'<p>لا توجد منتجات حاليًا.</p>'}</div><h3>${staff?'إدارة الطلبات':'طلباتي'}</h3>${!token?'<p>سجل دخول بديسكورد للشراء ومتابعة الطلبات.</p>':''}<div class="store-grid">${state.orders.slice().reverse().map(o=>`<article class="store-card"><h3>طلب #${o.number} • ${esc(o.product.name)}</h3><p>${labels[o.status]}</p>${staff?`<p>العميل: ${esc(o.username)} (${esc(o.discordId)})</p><p>رسالة ديسكورد: ${o.dmStatus==='sent'?'تم إرسالها':o.dmStatus==='failed'?'تعذر إرسالها، قد يكون الخاص مقفول':'قيد الإرسال'}</p>`:''}${detail(o.product)}${o.customerNote?`<p>ملاحظة العميل: ${esc(o.customerNote)}</p>`:''}${o.reason?`<p>سبب الرفض: ${esc(o.reason)}</p>`:''}${staff&&o.status==='pending'?`<button data-store="accept" data-id="${o.id}">قبول وفتح تذكرة</button><button data-store="reject" data-id="${o.id}">رفض بسبب</button>`:''}${o.ticketDeleted?'<p>تم حذف التذكرة.</p>':''}</article>`).join('')||'<p>لا توجد طلبات.</p>'}</div><h3>تذاكر الاستلام والدعم</h3><div class="store-grid">${state.tickets.map(t=>`<article class="store-card store-ticket"><h3>تذكرة طلب #${t.number} • ${labels[t.status]}</h3>${detail(t.product)}${t.customerNote?`<p>ملاحظة العميل: ${esc(t.customerNote)}</p>`:''}<div class="store-chat">${t.messages.map(m=>`<div class="store-message"><b>${m.sender==='support'?'الدعم':m.sender==='system'?'النظام':esc(m.name)}</b><small>${new Date(m.at).toLocaleString('ar-EG')}</small><p class="store-lines">${esc(m.text)}</p></div>`).join('')}</div>${t.status==='open'?`<form data-ticket="${t.id}"><textarea name="message" required maxlength="2000" placeholder="اكتب رسالتك للدعم"></textarea><button type="submit">إرسال</button></form><button data-store="close" data-id="${t.id}">إغلاق التذكرة</button>`:`<button data-store="delete" data-id="${t.id}">حذف التذكرة</button>`}</article>`).join('')||'<p>التذكرة هتظهر هنا بعد قبول الطلب.</p>'}</div>`;}
function modal(html){const d=document.createElement('dialog');d.className='store-dialog';d.dir='rtl';d.innerHTML=html;document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();d.querySelector('[data-cancel]').onclick=()=>d.close();return d;}
section.addEventListener('click',safe(async e=>{const b=e.target.closest('[data-store]');if(!b)return;const {store:action,id}=b.dataset;
 if(action==='edit'){const p=state.products.find(p=>p.id===id)||{};const d=modal(`<h3>${id?'تعديل':'إضافة'} منتج</h3><form>${[['name','اسم المنتج',true],['image','لينك الصورة',true],['price','السعر (اختياري)',false],['type','النوع (اختياري)',false],['delivery','طريقة الاستلام (اختياري)',false]].map(([n,l,r])=>`<label>${l}<input name="${n}" value="${esc(p[n]||'')}" ${r?'required':''}></label>`).join('')}<label>التفاصيل (اختياري)<textarea name="details">${esc(p.details||'')}</textarea></label><label>الملحوظة (اختياري)<textarea name="note">${esc(p.note||'')}</textarea></label><label><input name="active" type="checkbox" ${p.active!==false?'checked':''}> متاح في المتجر</label><button type="submit">حفظ</button><button type="button" data-cancel>إلغاء</button></form>`);d.querySelector('form').onsubmit=safe(async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=id||undefined;data.active=e.target.elements.active.checked;await post('/api/admin/store/products',data);d.close();await load();});return;}
 if(action==='buy'){if(!token){oauthLogin();return;}const p=state.products.find(x=>x.id===id);const d=modal(`<h3>تأكيد طلب الشراء</h3>${detail(p)}<p>بعد التأكيد طلبك هيكون قيد المراجعة. الاستلام بالتنسيق مع الدعم بعد القبول.</p><form><textarea name="note" maxlength="2000" placeholder="ملاحظة للدعم (اختياري)"></textarea><button type="submit">تأكيد الشراء</button><button type="button" data-cancel>إلغاء</button></form>`);d.querySelector('form').onsubmit=safe(async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{const r=await post('/api/store/orders',{productId:id,note:new FormData(e.target).get('note')});d.close();toast(r.dmSent?'طلبك قيد المراجعة، واتبعثلك في الخاص':'طلبك قيد المراجعة. تعذر إرسال رسالة ديسكورد');await load();}finally{btn.disabled=false;}});return;}
 b.disabled=true;try{if(action==='hide'){if(!confirm('إخفاء المنتج من المتجر؟'))return;await api('/api/admin/store/products/'+id,{method:'DELETE'});}else if(['accept','reject'].includes(action)){let reason='';if(action==='reject'){reason=prompt('سبب رفض الطلب؟');if(!reason?.trim())return;}else if(!confirm('قبول الطلب وفتح تذكرة الاستلام؟'))return;const r=await post('/api/admin/store/orders/'+id+'/review',{action:action==='accept'?'accept':'reject',reason});toast(r.dmSent?'تم تحديث الطلب وإرسال رسالة ديسكورد':'تم تحديث الطلب، لكن تعذر إرسال رسالة ديسكورد');}else{if(!confirm(action==='delete'?'حذف التذكرة والمحادثة نهائيًا؟':'إغلاق التذكرة؟'))return;await post('/api/store/tickets/'+id+'/action',{action});}await load();}finally{b.disabled=false;}}));
section.addEventListener('submit',safe(async e=>{const f=e.target;if(!f.dataset.ticket)return;e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{await post('/api/store/tickets/'+f.dataset.ticket+'/messages',{message:new FormData(f).get('message')});await load();}finally{b.disabled=false;}}));
// Add the store management entry each time the existing admin panel renders.
const panel=document.querySelector('#adminBox');if(panel)new MutationObserver(()=>{if(!panel.querySelector('[data-store-admin]')){const a=document.createElement('a');a.href='#store';a.dataset.storeAdmin='1';a.className='btn primary';a.textContent='إدارة المتجر والطلبات والتذاكر';a.onclick=()=>safe(load)();panel.prepend(a);}}).observe(panel,{childList:true});
window.addEventListener('hashchange',()=>{if(location.hash==='#store')safe(load)();});
setTimeout(()=>safe(load)(),1200);setInterval(()=>{if(location.hash==='#store'&&!document.querySelector('.store-dialog')&&!section.querySelector('textarea:focus'))safe(load)();},12000);
})();
